[project]
name = 'Parallel-Universe-Collaboration-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.cross-reality-data-sync]
path = 'contracts/cross-reality-data-sync.clar'
clarity_version = 2
epoch = 2.5

[contracts.divergence-point-management]
path = 'contracts/divergence-point-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.inter-universal-identification]
path = 'contracts/inter-universal-identification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
